name: NEnderChest
main: wtf.n1zamu.NEnderChest

author: [ n1zamu, Twice]

version: '${project.version}'
api-version: '1.16'

commands:
  nEnderChest:

permissions:
  nEnderChest:
    give:
    check:
    wipe:
    open:
    clear: