name: NEnderChest
version: '${project.version}'
main: wtf.n1zamu.NEnderChest
api-version: '1.16'
commands:
  nEnderChest:
permissions:
  nEnderChest:
    give:
    check:
    wipe:
    open:
    clear: